name: ESDE GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [ push ]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world!
        run: date
      # ADD SOME CUSTOM UNIQUE CODE HERE!!!!
      - name: Printing job status
        run: echo "ğŸ This job's status is ${{ job.status }}."
